#!/usr/bin/env python3
import argparse
import gzip
import json
import os
from datetime import datetime

from matrix_value_types import VALUE_TYPES, require_nonnegative

progress_every_rows = 1000


def parse_float(value):
    if value in ('', 'NA', 'nan'):
        return 0.0
    return float(value)


def convert(matrix_tsv, out_dir, value_type):
    os.makedirs(out_dir, exist_ok=True)
    entries_path = f'{out_dir}/entries.tsv'
    genes = []
    has_negative = False
    nnz = 0
    gene_idx = 0

    with gzip.open(matrix_tsv, 'rt') as handle, open(entries_path, 'w') as entries:
        cells = handle.readline().rstrip('\n').split('\t')[1:]
        for line in handle:
            if not line.strip():
                continue
            gene_idx += 1
            gene, *values = line.rstrip('\n').split('\t')
            if len(values) != len(cells):
                raise SystemExit(f'Row {gene_idx + 1} has {len(values)} values but expected {len(cells)}')
            genes.append(gene)
            for cell_idx, raw_value in enumerate(values, start=1):
                value = parse_float(raw_value)
                if value == 0:
                    continue
                if value < 0:
                    has_negative = True
                nnz += 1
                entries.write(f'{gene_idx}\t{cell_idx}\t{value:.12g}\n')
            if gene_idx % progress_every_rows == 0:
                print(f'[convert-expression] processed {gene_idx} rows; nnz={nnz}', flush=True)

    require_nonnegative(has_negative, value_type)

    with gzip.open(f'{out_dir}/matrix.mtx.gz', 'wt') as out, open(entries_path) as entries:
        out.write('%%MatrixMarket matrix coordinate real general\n')
        out.write('% generated by convert_expression_tsv_to_sparse_10x.py\n')
        out.write(f'{len(genes)} {len(cells)} {nnz}\n')
        out.writelines(entries)
    os.remove(entries_path)

    with gzip.open(f'{out_dir}/features.tsv.gz', 'wt') as out:
        out.writelines(f'{gene}\t{gene}\tGene Expression\n' for gene in genes)
    with gzip.open(f'{out_dir}/barcodes.tsv.gz', 'wt') as out:
        out.writelines(f'{cell}\n' for cell in cells)

    with open(f'{out_dir}/matrix_value_type.json', 'w') as f:
        json.dump({
            'value_type': value_type,
            'n_genes': len(genes),
            'n_cells': len(cells),
            'nnz': nnz,
            'timestamp': datetime.now().isoformat(timespec='seconds'),
        }, f, indent=2)

    print(f'Wrote {out_dir} with {len(genes)} genes, {len(cells)} cells, {nnz} nonzero values, value_type={value_type}')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--matrix-tsv', required=True)
    parser.add_argument('--out-dir', required=True)
    parser.add_argument('--orientation', required=True, choices=['gene_by_cell'])
    parser.add_argument('--value-type', required=True, choices=sorted(VALUE_TYPES))
    args = parser.parse_args()
    convert(args.matrix_tsv, args.out_dir, args.value_type)


if __name__ == '__main__':
    main()
