#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(Matrix)
  library(Seurat)
})

parse_args <- function(argv) {
  args <- list(
    assay = NA_character_,
    counts_layer = "counts",
    cell_filter_col = NA_character_,
    cell_filter_values = NA_character_,
    min_detection = "0",
    cell_id_col = "cell_id"
  )
  i <- 1
  while (i <= length(argv)) {
    key <- argv[[i]]
    if (!grepl("^--", key)) {
      stop("Unexpected positional argument: ", key, call. = FALSE)
    }
    if (i == length(argv)) {
      stop("Missing value for ", key, call. = FALSE)
    }
    name <- gsub("-", "_", sub("^--", "", key))
    args[[name]] <- argv[[i + 1]]
    i <- i + 2
  }
  args
}

usage <- function() {
  cat(
    paste(
      "Usage:",
      "  export_rank_universe_10x_from_seurat.R --rds map.rds --out-dir rank_10x",
      "",
      "Optional:",
      "  --assay RNA",
      "  --counts-layer counts",
      "  --cell-filter-col cell_type --cell-filter-values 'Type A,Type B'",
      "  --min-detection 0.01",
      sep = "\n"
    ),
    "\n"
  )
}

split_csv <- function(value) {
  if (is.na(value) || !nzchar(value)) {
    return(character())
  }
  trimws(strsplit(value, ",", fixed = TRUE)[[1]])
}

write_gz_lines <- function(lines, path) {
  con <- gzfile(path, open = "wt")
  on.exit(close(con), add = TRUE)
  writeLines(lines, con)
}

write_tsv_gz <- function(df, path) {
  con <- gzfile(path, open = "wt")
  on.exit(close(con), add = TRUE)
  write.table(df, con, sep = "\t", quote = FALSE, row.names = FALSE, na = "")
}

get_assay_matrix <- function(obj, assay, layer) {
  tryCatch(
    GetAssayData(obj, assay = assay, layer = layer),
    error = function(e) GetAssayData(obj, assay = assay, slot = layer)
  )
}

args <- parse_args(commandArgs(trailingOnly = TRUE))
required <- c("rds", "out_dir")
missing <- required[vapply(required, function(name) {
  value <- args[[name]]
  is.null(value) || is.na(value) || !nzchar(value)
}, logical(1))]
if (length(missing) > 0) {
  usage()
  stop("Missing required argument(s): ", paste(missing, collapse = ", "), call. = FALSE)
}

min_detection <- as.numeric(args$min_detection)
if (!is.finite(min_detection) || min_detection < 0 || min_detection > 1) {
  stop("--min-detection must be between 0 and 1", call. = FALSE)
}

dir.create(args$out_dir, recursive = TRUE, showWarnings = FALSE)

message("Reading Seurat object: ", args$rds)
obj <- readRDS(args$rds)
assay <- args$assay
if (is.na(assay) || !nzchar(assay)) {
  assay <- DefaultAssay(obj)
}
message("Using assay=", assay, " layer/slot=", args$counts_layer)

counts <- get_assay_matrix(obj, assay, args$counts_layer)
if (!inherits(counts, "sparseMatrix")) {
  counts <- as(counts, "dgCMatrix")
}

meta <- obj@meta.data
meta[[args$cell_id_col]] <- rownames(meta)
if (!is.na(args$cell_filter_col) && nzchar(args$cell_filter_col)) {
  if (!args$cell_filter_col %in% names(meta)) {
    stop("Cell filter column not found in metadata: ", args$cell_filter_col, call. = FALSE)
  }
  filter_values <- split_csv(args$cell_filter_values)
  if (length(filter_values) == 0) {
    stop("--cell-filter-values is required when --cell-filter-col is set", call. = FALSE)
  }
  meta <- meta[meta[[args$cell_filter_col]] %in% filter_values, , drop = FALSE]
}

cells <- intersect(meta[[args$cell_id_col]], colnames(counts))
if (length(cells) == 0) {
  stop("No selected metadata cells were present in the expression matrix", call. = FALSE)
}

counts <- counts[, cells, drop = FALSE]
library_size <- Matrix::colSums(counts)
detection_fraction <- Matrix::rowMeans(counts > 0)
keep_genes <- names(detection_fraction)[is.finite(detection_fraction) & detection_fraction >= min_detection]
keep_genes <- intersect(keep_genes, rownames(counts))
if (length(keep_genes) == 0) {
  stop("No genes passed --min-detection", call. = FALSE)
}
counts <- as(counts[keep_genes, , drop = FALSE], "dgCMatrix")

message("Writing rank-universe sparse count matrix: ", nrow(counts), " genes x ", ncol(counts), " cells")
write_gz_lines(paste(rownames(counts), rownames(counts), "Gene Expression", sep = "\t"), file.path(args$out_dir, "features.tsv.gz"))
write_gz_lines(colnames(counts), file.path(args$out_dir, "barcodes.tsv.gz"))
write_tsv_gz(
  data.frame(cell_id = colnames(counts), total_counts = as.numeric(library_size), stringsAsFactors = FALSE),
  file.path(args$out_dir, "cell_total_counts.tsv.gz")
)

mtx_path <- file.path(args$out_dir, "matrix.mtx.gz")
con <- gzfile(mtx_path, open = "wt")
on.exit(close(con), add = TRUE)
writeLines("%%MatrixMarket matrix coordinate integer general", con)
writeLines("% Generated by export_rank_universe_10x_from_seurat.R", con)
writeLines(paste(nrow(counts), ncol(counts), length(counts@x)), con)
for (j in seq_len(ncol(counts))) {
  start <- counts@p[[j]] + 1L
  end <- counts@p[[j + 1L]]
  if (start <= end) {
    rows <- counts@i[start:end] + 1L
    vals <- counts@x[start:end]
    writeLines(paste(rows, j, vals), con)
  }
}
close(con)

summary <- data.frame(
  metric = c("n_genes", "n_cells", "min_detection", "nnz", "assay", "counts_layer"),
  value = c(nrow(counts), ncol(counts), min_detection, length(counts@x), assay, args$counts_layer)
)
write.table(summary, file.path(args$out_dir, "rank_universe_summary.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
message("Done")
